# Nom du workflow
name: Deploy Jupyter Book

# Déclencheur : se lance à chaque push sur la branche main
on:
  push:
    branches: [ main ]

# Tâches à exécuter
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Build the Jupyter Book
      run: |
        jupyter-book build .

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
